language: c

compiler:
  - clang
  - gcc

before_install:
  - git clone https://github.com/troydhanson/uthash
  - sudo cp uthash/src/* /usr/local/include
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script: cmake . && make

env:
  global:
    - secure: "G86i16M1pF9V7YEeKavKJmr6wQUqeBR1amUDZTZ6RJFLVQlzgsCsRJCNBm4saDHb4fF3MZoCMPwQOn6gb2X6uXvDfglib42IFjH2FUknYcmi+aWEayIvzr+CgdY6HF0vD31bQ4P355/ydKQ3Qg8l7aIv60Pk33uTEPuH89/WZRG3l3tTzpJgDPlr7s7chM7pZYhWBhc+CMwMYY4kkpnpnu81oRDjyYNpnVNzNObguLwz1zM0nRJUZ5VcALLRTZsckTVo+2ht8FN/vbsls366wtIqwwFQ3uXd+lxJXzfyn+Zr9JYbX5gFz7BymnDRYng000pPP2bJ4GEfANZVT0zyxFj9MwCoEgvpUSnsyl4ZGXdnRWDdhZNl6UvCdSM3yZ8x9zwGfBqXp7Vm72rdpwU5kbvn0N3uRp5I4LEUn4T4wPuoygCQc8cKP/nfl2nJtFRpga1FDDkaPjb8vTEOld0NDt6WULnGWzjxMaAxiLBUNzx5F+Y6ZujL4lLs79HdsYfQo0xygKQwr/paNWPb1heNV4WDHX8bi+Sq17rp582E6jU01gJc6KeU+31kqftK0unLXsPejAE72KsSVGH7GuFxRHo9Md6bC5cEBJQOeXAS6Si8vpMX5qF2OIsft7u14ljt4mpXQGPMRvUtOFJb4gBJ+bvyvmhA8VV70jxyUHJLeoY="

addons:
  coverity_scan:
    project:
      name: "fcambus/statzone"
      version: 1.0.0
      description: "DNS zone file analyzer targeted at TLD zones"
    notification_email: fred@statdns.com
    build_command_prepend: cmake .
    build_command: make -j 4
    branch_pattern: c
